remote_theme: BDHU/minimalist

title: Digital Portfolio
description: This is my digital portfolio of my data science work
logo: /img/this (2).jpg

color-scheme: dark



plugins:
- jekyll-remote-theme
