theme: jekyll-theme-minimal
title: Digital Portfolio
description: This is my digital portfolio of my data science work


navbar-links:
  About Me: "aboutme"
  Resources: "Data_Science"


avatar: "/_Images/this%20(2).jpg"
